### ISSUE TITLE
App crash loop

### ISSUE THREAD

**Issue by solsebas** [RyanYuuki/AnymeX#181]
### Steps to Reproduce

1. Open app
2. Click on user icon in upper right corner
3. Click "Change service"
4. Choose "Extensions"

### Expected Outcome

App shouldn't crash.

### Actual Outcome

The app crashes without any error window and from now on it crashes every time I just open it unless reinstalled.

### Error Logs (if applicable)

I cannot enter app so unable to export logs.

### AnymeX Version

2.9.9 & 3.0.1

### Operating System Version

Android 15

### Device Information

Samsung Galaxy S24 Ultra

### Submission Checklist

- [x] I have searched existing issues to confirm this is not a duplicate.
- [x] I am using the **[latest](https://github.com/RyanYuuki/AnymeX/releases/latest)** version of AnymeX. If not, I have provided a reason for not updating.
- [ ] If this is an issue with an extension, I should be opening an issue in the extension's repository.

**Comment by itsmechinmoy** [comment]
should be fixed

**Comment by solsebas** [comment]
tried again on v3.0,1-hotfix and still crashes every time :(

**Comment by itsmechinmoy** [comment]
how about sending logs?

**Comment by solsebas** [comment]
How can I export them if app crashes every time **after** I enter "Extensions" once? Even if I force stop it in android options. Is there a way?

**Comment by itsmechinmoy** [comment]
> How can I export them if app crashes every time **after** I enter "Extensions" once? Even if I force stop it in android options. Is there a way?

logfox

**Comment by itsmechinmoy** [comment]
also its fixed, all you need to do is clear data of the app
